spring:
  application:
    name: jwt-redis-server
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:postgresql://127.0.0.1:6432/auth
    username: root
    password: a1234567!
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

setting:
  db:
    migration: true