spring:
  application:
    name: jwt-redis-server
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/root
    username: root
    password: 1111
